//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMY.WEB.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/FMY.WEB.Model")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ActiveTimeField;
        
        private System.DateTime CreateTimeField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private int SexField;
        
        private bool StatusField;
        
        private System.DateTime UpdateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActiveTime
        {
            get
            {
                return this.ActiveTimeField;
            }
            set
            {
                this.ActiveTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateTime
        {
            get
            {
                return this.UpdateTimeField;
            }
            set
            {
                this.UpdateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRegistEmail", Namespace="http://schemas.datacontract.org/2004/07/FMY.WEB.Model")]
    public partial class UserRegistEmail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime SendTimeField;
        
        private int StatusField;
        
        private int UserIdField;
        
        private string ValidateCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime
        {
            get
            {
                return this.SendTimeField;
            }
            set
            {
                this.SendTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidateCode
        {
            get
            {
                return this.ValidateCodeField;
            }
            set
            {
                this.ValidateCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService", SessionMode=System.ServiceModel.SessionMode.Required)]
public interface CalculatorService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/Add", ReplyAction="http://tempuri.org/CalculatorService/AddResponse")]
    int Add(int i, int j);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/Add", ReplyAction="http://tempuri.org/CalculatorService/AddResponse")]
    System.Threading.Tasks.Task<int> AddAsync(int i, int j);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/InsertUser", ReplyAction="http://tempuri.org/CalculatorService/InsertUserResponse")]
    int InsertUser(FMY.WEB.Model.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/InsertUser", ReplyAction="http://tempuri.org/CalculatorService/InsertUserResponse")]
    System.Threading.Tasks.Task<int> InsertUserAsync(FMY.WEB.Model.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/InserRegistEmail", ReplyAction="http://tempuri.org/CalculatorService/InserRegistEmailResponse")]
    int InserRegistEmail(FMY.WEB.Model.UserRegistEmail userRegistEmailModel);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/InserRegistEmail", ReplyAction="http://tempuri.org/CalculatorService/InserRegistEmailResponse")]
    System.Threading.Tasks.Task<int> InserRegistEmailAsync(FMY.WEB.Model.UserRegistEmail userRegistEmailModel);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/InsertUserNoTrans", ReplyAction="http://tempuri.org/CalculatorService/InsertUserNoTransResponse")]
    int InsertUserNoTrans(FMY.WEB.Model.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatorService/InsertUserNoTrans", ReplyAction="http://tempuri.org/CalculatorService/InsertUserNoTransResponse")]
    System.Threading.Tasks.Task<int> InsertUserNoTransAsync(FMY.WEB.Model.User user);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CalculatorServiceChannel : CalculatorService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<CalculatorService>, CalculatorService
{
    
    public CalculatorServiceClient()
    {
    }
    
    public CalculatorServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Add(int i, int j)
    {
        return base.Channel.Add(i, j);
    }
    
    public System.Threading.Tasks.Task<int> AddAsync(int i, int j)
    {
        return base.Channel.AddAsync(i, j);
    }
    
    public int InsertUser(FMY.WEB.Model.User user)
    {
        return base.Channel.InsertUser(user);
    }
    
    public System.Threading.Tasks.Task<int> InsertUserAsync(FMY.WEB.Model.User user)
    {
        return base.Channel.InsertUserAsync(user);
    }
    
    public int InserRegistEmail(FMY.WEB.Model.UserRegistEmail userRegistEmailModel)
    {
        return base.Channel.InserRegistEmail(userRegistEmailModel);
    }
    
    public System.Threading.Tasks.Task<int> InserRegistEmailAsync(FMY.WEB.Model.UserRegistEmail userRegistEmailModel)
    {
        return base.Channel.InserRegistEmailAsync(userRegistEmailModel);
    }
    
    public int InsertUserNoTrans(FMY.WEB.Model.User user)
    {
        return base.Channel.InsertUserNoTrans(user);
    }
    
    public System.Threading.Tasks.Task<int> InsertUserNoTransAsync(FMY.WEB.Model.User user)
    {
        return base.Channel.InsertUserNoTransAsync(user);
    }
}
